version: '3.8'

services:
  app:
    build: .
    ports:
      - 8082:8082
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/flight?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=mysql_user
      - SPRING_DATASOURCE_PASSWORD=password

  db:
    image: "mysql:8.0"
    container_name: "mysql_container"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=flight
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "mysql_user", "-p$password"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_data:
